stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script:
        - env
    - stage: deploy
      if: branch = master
      if: type != pull_request
      script:
        - eval "$(ssh-agent -s)" # start the ssh agent
        - echo -e $RESIN_DEPLOY_KEY > id_rsa
        - chmod 0600 id_rsa
        - ssh-add ./id_rsa
        - cat resinkey >> ~/.ssh/known_hosts
        - git remote add resin $RESIN_REMOTE
        - git push -f resin master
